# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyungmook Choi
title: Ph.D. student
email: kyungmook.choi@yonsei.ac.kr
website: www.github.com/chkmook

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: chkmook
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: soundcloud
  icon: fab fa-soundcloud
  url: https://soundcloud.com/chkmook
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Ph.D. student at Visual Intelligence Lab in Yonsei University under the supervision of prof. Youngjung Uh. I'm interested in 3D-aware GAN and image editing.

#   I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Visual Intelligence Lab @Yonsei University
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: UNDERGRADUATE INTERN
        caption: February 2021 - August 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Undergraduate Intern
            
      - layout: left
        title: Computer Vision Lab @Yonsei University
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: UNDERGRADUATE INTERN
        caption: July 2020 - December 2020
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Undergraduate Intern

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Yonsei University
        caption: August 2021 - Present
        sub_title: Seoul, Korea
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Joint course of M.S./Ph.D degrees in Department of Artificial Intelligence
          
      - layout: left
        title: Yonsei University
        caption: March 2015 - August 2021
        sub_title: Seoul, Korea
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Bachelor in School of Electrical and Electronic Engineering
          
      - layout: left
        title: Gyeonggibuk Science High School
        caption: March 2013 - January 2015
        sub_title: Uijeongbu, Gyeonggi-do, Korea
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   Bachelor in School of Electrical and Electronic Engineering

  - title: Awards & Certifications
    layout: text
    content:
      Excellent scholarship for admission, Yonsei University, Korea - 2015

  - title: Teachings
    layout: text
    content:
      Intro. to Artificial Intelligence (TA), Yonsei University, 2021-2

  - title: Skills
    layout: text
    content:
      C, Matlab, Python, Pytorch

    # content: | # this will include new lines to allow paragraphs
    #   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    #   - Rock climbing
    #   - Gaming
    #   - Knitting
    #   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #   Look at this cool image  
    #   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
